pipeline {
  agent {
    docker {
            image 'node:14-alpine'
            args '-v $HOME:/home/jenkins'
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
